apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    app: hello-world-flask
spec:
  containers:
  - name: hello-world-flask
    image: edwinko/hello-world-flask:latest
    ports:
    - containerPort: 8000